package com.lftechnology.sbwbtraining.division.model.impl;

import com.lftechnology.sbwbtraining.division.model.Division;
import com.lftechnology.sbwbtraining.division.service.DivisionLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Division service. Represents a row in the &quot;MO_Division&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DivisionImpl}.
 * </p>
 *
 * @author Sanjib Maharjan
 * @see DivisionImpl
 * @see com.lftechnology.sbwbtraining.division.model.Division
 * @generated
 */
public abstract class DivisionBaseImpl extends DivisionModelImpl
    implements Division {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a division model instance should use the {@link Division} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            DivisionLocalServiceUtil.addDivision(this);
        } else {
            DivisionLocalServiceUtil.updateDivision(this);
        }
    }
}
