package com.lftechnology.sbwbtraining.division.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Division service. Represents a row in the &quot;MO_Division&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lftechnology.sbwbtraining.division.model.impl.DivisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lftechnology.sbwbtraining.division.model.impl.DivisionImpl}.
 * </p>
 *
 * @author Sanjib Maharjan
 * @see Division
 * @see com.lftechnology.sbwbtraining.division.model.impl.DivisionImpl
 * @see com.lftechnology.sbwbtraining.division.model.impl.DivisionModelImpl
 * @generated
 */
public interface DivisionModel extends BaseModel<Division> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a division model instance should use the {@link Division} interface instead.
     */

    /**
     * Returns the primary key of this division.
     *
     * @return the primary key of this division
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this division.
     *
     * @param primaryKey the primary key of this division
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the division ID of this division.
     *
     * @return the division ID of this division
     */
    public long getDivisionId();

    /**
     * Sets the division ID of this division.
     *
     * @param divisionId the division ID of this division
     */
    public void setDivisionId(long divisionId);

    /**
     * Returns the division name of this division.
     *
     * @return the division name of this division
     */
    @AutoEscape
    public String getDivisionName();

    /**
     * Sets the division name of this division.
     *
     * @param divisionName the division name of this division
     */
    public void setDivisionName(String divisionName);

    /**
     * Returns the created by of this division.
     *
     * @return the created by of this division
     */
    @AutoEscape
    public String getCreatedBy();

    /**
     * Sets the created by of this division.
     *
     * @param createdBy the created by of this division
     */
    public void setCreatedBy(String createdBy);

    /**
     * Returns the created on of this division.
     *
     * @return the created on of this division
     */
    @AutoEscape
    public String getCreatedOn();

    /**
     * Sets the created on of this division.
     *
     * @param createdOn the created on of this division
     */
    public void setCreatedOn(String createdOn);

    /**
     * Returns the company ID of this division.
     *
     * @return the company ID of this division
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this division.
     *
     * @param companyId the company ID of this division
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this division.
     *
     * @return the group ID of this division
     */
    public long getGroupId();

    /**
     * Sets the group ID of this division.
     *
     * @param groupId the group ID of this division
     */
    public void setGroupId(long groupId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Division division);

    public int hashCode();

    public CacheModel<Division> toCacheModel();

    public Division toEscapedModel();

    public Division toUnescapedModel();

    public String toString();

    public String toXmlString();
}
