package com.lftechnology.sbwbtraining.userapplication.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Emp service. Represents a row in the &quot;MO_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lftechnology.sbwbtraining.userapplication.model.impl.EmpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lftechnology.sbwbtraining.userapplication.model.impl.EmpImpl}.
 * </p>
 *
 * @author Bibhushan Joshi
 * @see Emp
 * @see com.lftechnology.sbwbtraining.userapplication.model.impl.EmpImpl
 * @see com.lftechnology.sbwbtraining.userapplication.model.impl.EmpModelImpl
 * @generated
 */
public interface EmpModel extends BaseModel<Emp> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a emp model instance should use the {@link Emp} interface instead.
     */

    /**
     * Returns the primary key of this emp.
     *
     * @return the primary key of this emp
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this emp.
     *
     * @param primaryKey the primary key of this emp
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the user ID of this emp.
     *
     * @return the user ID of this emp
     */
    public long getUserId();

    /**
     * Sets the user ID of this emp.
     *
     * @param userId the user ID of this emp
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this emp.
     *
     * @return the user uuid of this emp
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this emp.
     *
     * @param userUuid the user uuid of this emp
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the first name of this emp.
     *
     * @return the first name of this emp
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this emp.
     *
     * @param firstName the first name of this emp
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this emp.
     *
     * @return the last name of this emp
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this emp.
     *
     * @param lastName the last name of this emp
     */
    public void setLastName(String lastName);

    /**
     * Returns the address of this emp.
     *
     * @return the address of this emp
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this emp.
     *
     * @param address the address of this emp
     */
    public void setAddress(String address);

    /**
     * Returns the phone number of this emp.
     *
     * @return the phone number of this emp
     */
    @AutoEscape
    public String getPhoneNumber();

    /**
     * Sets the phone number of this emp.
     *
     * @param phoneNumber the phone number of this emp
     */
    public void setPhoneNumber(String phoneNumber);

    /**
     * Returns the email of this emp.
     *
     * @return the email of this emp
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this emp.
     *
     * @param email the email of this emp
     */
    public void setEmail(String email);

    /**
     * Returns the company name of this emp.
     *
     * @return the company name of this emp
     */
    @AutoEscape
    public String getCompanyName();

    /**
     * Sets the company name of this emp.
     *
     * @param companyName the company name of this emp
     */
    public void setCompanyName(String companyName);

    /**
     * Returns the dep ID of this emp.
     *
     * @return the dep ID of this emp
     */
    public long getDepId();

    /**
     * Sets the dep ID of this emp.
     *
     * @param depId the dep ID of this emp
     */
    public void setDepId(long depId);

    /**
     * Returns the user desc of this emp.
     *
     * @return the user desc of this emp
     */
    @AutoEscape
    public String getUserDesc();

    /**
     * Sets the user desc of this emp.
     *
     * @param userDesc the user desc of this emp
     */
    public void setUserDesc(String userDesc);

    /**
     * Returns the status of this emp.
     *
     * @return the status of this emp
     */
    public Boolean getStatus();

    /**
     * Sets the status of this emp.
     *
     * @param status the status of this emp
     */
    public void setStatus(Boolean status);

    /**
     * Returns the company ID of this emp.
     *
     * @return the company ID of this emp
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this emp.
     *
     * @param companyId the company ID of this emp
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this emp.
     *
     * @return the group ID of this emp
     */
    public long getGroupId();

    /**
     * Sets the group ID of this emp.
     *
     * @param groupId the group ID of this emp
     */
    public void setGroupId(long groupId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Emp emp);

    public int hashCode();

    public CacheModel<Emp> toCacheModel();

    public Emp toEscapedModel();

    public Emp toUnescapedModel();

    public String toString();

    public String toXmlString();
}
