package com.lftechnology.sbwbtraining.userapplication.model.impl;

import com.lftechnology.sbwbtraining.userapplication.model.Emp;
import com.lftechnology.sbwbtraining.userapplication.service.EmpLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Emp service. Represents a row in the &quot;MO_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpImpl}.
 * </p>
 *
 * @author Bibhushan Joshi
 * @see EmpImpl
 * @see com.lftechnology.sbwbtraining.userapplication.model.Emp
 * @generated
 */
public abstract class EmpBaseImpl extends EmpModelImpl implements Emp {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a emp model instance should use the {@link Emp} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            EmpLocalServiceUtil.addEmp(this);
        } else {
            EmpLocalServiceUtil.updateEmp(this);
        }
    }
}
